version: 1.0.{build}
image: Visual Studio 2017 Preview
# Set "build version number" to "short-commit-hash" or when tagged to "tag name" (Travis style)
init:
  - ps: >-
      if ($env:APPVEYOR_REPO_TAG -eq "true")
      {
        Update-AppveyorBuild -Version "$env:APPVEYOR_REPO_TAG_NAME"
      }
      else
      {
        Update-AppveyorBuild -Version "0.0.0-$env:APPVEYOR_REPO_BRANCH-$($env:APPVEYOR_REPO_COMMIT.substring(0,8))"
      }
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'

before_build:
- cmd: dotnet restore
build:
  project: diffstore.sln
  verbosity: minimal
test_script:
- cmd: >-
    cd Diffstore.Tests

    dotnet test

    cd ../
artifacts:
- path: '**\*.nupkg'
deploy:
- provider: NuGet
  api_key:
    secure: QEbJDFQZ7kaOSNB0GzWwcYQcb80yIYWQGuB26aLioZdFwRROZALcaGarK/TSQVkX
  on:
    APPVEYOR_REPO_TAG: true
